AY2324S1-CS2113-W12-1/tp

.gitignore
src/main/java/Quizhub.java
src/main/java/quizhub/command/Command.java
src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java
tasklist.txt

Added Command edit and storage

Added CommandEdit, Implemented Storage

---

src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/ui/Ui.java
tasklist.txt

- Command Start to enter Quiz Mode
- In quiz mode, compare answers by .equal() in v1.0
- Quiz mode will end if user exits the program or when the user finishes answering all questions in the question bank (array list)

Branch quiz mode

---

src/main/java/quizhub/command/CommandHelp.java
src/main/java/quizhub/ui/Ui.java

- updated UI intro message and exit message
- added help command

updated UI and help command

---

src/main/java/quizhub/command/CommandShortAnswer.java
src/test/java/quizhub/parser/ParserTest.java
src/test/java/quizhub/questionlist/QuestionListTest.java

Add JUnit CommandShortAnswer, Add JUnit addToQuestionList

---

src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/StartTest.java
src/test/java/quizhub/parser/QuestionListTest.java
tasklist.txt

introduce 3 tests for the Command Start Quiz feature
- testAddQuestionToListAndStorage
- testStartQuizWithQuestions
- testStartQuizWithNoQuestions

Branch StartTest

---

src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandListTest.java

Add JUnit CommandEdit, Add JUnit CommandList, Adjust Question Description Display Format

---

src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java

Bug 1 - Add question has uncaught exceptions, fixed by checking for null
Bug 2 - Taking quiz may output wrong for white spaces in answers

Fix minor bugs in adding questions and taking quiz

---

src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/test/java/quizhub/command/CommandDeleteTest.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandFindTest.java
src/test/java/quizhub/command/CommandHelpTest.java
src/test/java/quizhub/command/CommandListTest.java
src/test/java/quizhub/questionlist/QuestionListTest.java

1. Add module attribute to question and search by module function
2. Fixed affected JUnit test cases

Add module attribute to question and search by module function

---

src/main/java/quizhub/command/CommandShuffle.java
src/main/java/quizhub/logger/CustomLogger.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/questionlist/QuestionList.java

Add Shuffle, Find

---

src/main/java/quizhub/command/Command.java
src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandHelp.java
src/main/java/quizhub/command/CommandInvalid.java
src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java
src/test/java/quizhub/command/CommandDeleteTest.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandFindTest.java
src/test/java/quizhub/command/CommandHelpTest.java
src/test/java/quizhub/command/CommandListTest.java
src/test/java/quizhub/command/StartTest.java
src/test/java/quizhub/questionlist/QuestionListTest.java

Added question difficulty levels

---

src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/questionlist/QuestionList.java
src/test/java/quizhub/command/StartTest.java

Added categorisation to organise quiz questions by module

---

src/main/java/quizhub/storage/Storage.java

Abstract functions for lower nesting level
Improve error handling for file parsing cases
Improve program logic

Improve code quality in /storage/Storage.java

---

src/main/java/quizhub/storage/Storage.java

Ensure questions conform to the 3 difficulty levels by calling the parser class

Handle invalid question difficulty levels when reading from storage

---

src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java

Reverts AY2324S1-CS2113-W12-1/tp#64

Revert "Branch random qns start"

---

src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java
src/test/java/quizhub/parser/ParserTest.java

Refactor code in parser and commands

---

src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandFindTest.java

Refactor parsing elements from CommandEdit to Parser
Fixed tests for CommandFind and CommandEdit

Refactor parsing elements from CommandEdit to Parser

---

docs/UserGuide.md

Add user guide for 'delete' and 'find' commands

Add user guide for 'delete' and 'find' commands

---

src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandHelpTest.java

Reinforce command edit mark

---

src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandHelpTest.java
src/test/java/quizhub/command/CommandMarkTest.java

Reinforced Bug Checks for CommandEdit and CommandMarkDifficulty, Updated tests for both commands

---

docs/UserGuide.md
src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandExit.java
src/main/java/quizhub/command/CommandFind.java
src/main/java/quizhub/command/CommandHelp.java
src/main/java/quizhub/command/CommandInvalid.java
src/main/java/quizhub/command/CommandList.java
src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/command/CommandShortAnswer.java
src/main/java/quizhub/command/CommandShuffle.java
src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/questionlist/QuestionList.java

Update user guide and code quality

---

.gitignore
docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/Quizhub.java
src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandFind.java
src/main/java/quizhub/command/CommandHelp.java
src/main/java/quizhub/command/CommandList.java
src/main/java/quizhub/command/CommandShortAnswer.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/ui/Ui.java
text-ui-test/EXPECTED.TXT

closes #127 
tasklist.txt -> questionlist.txt
duke -> quizhub
task(s) -> question(s)

Rename any instance of legacy names "duke" and "task"

---

src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/exception/QuizHubExceptions.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/storage/Storage.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandDeleteTest.java

minor code refactoring

---

docs/DeveloperGuide.md

Update DG for version 2.0 release

---

src/main/java/quizhub/command/CommandMultipleChoice.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/MultipleChoiceQn.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java

Halfway implement MCQ feature

---

src/main/java/Quizhub.java
src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/command/CommandMultipleChoice.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/MultipleChoiceQn.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java

Add MCQ class, command, edit, and parse methods

Add MCQ class, command, edit and parse methods

---

docs/UserGuide.md
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/test/java/quizhub/command/CommandDeleteTest.java
src/test/java/quizhub/parser/ParserTest.java

close #153 - Add escape sequence \slash
close #159 - Add escape sequence \slash
Also removed potential illegal character "|" 
User guide is updated with the latest information.

Allow forward slash through escape characters

---

docs/UserGuide.md
src/main/java/quizhub/command/CommandShortAnswer.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/storage/Storage.java

close #182 - Default parsing of done/undone field to undone upon invalidity. Ignore questions with invalid difficulty.
close #181 - Fix case sensitivity of done/undone field in storage file.

Fix issues when loading from storage file

---

src/main/java/quizhub/command/CommandEdit.java
src/main/java/quizhub/command/CommandMultipleChoice.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/MultipleChoiceQn.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandFindTest.java
src/test/java/quizhub/command/CommandHelpTest.java
src/test/java/quizhub/command/CommandListTest.java

Fix bugs related to the parsing of the edit command for MCQ and loading of questions from storage
Update some test cases (TBC)

Bug fix for MCQ parsing and storage

---

src/main/java/quizhub/command/CommandMarkDifficulty.java
src/main/java/quizhub/command/CommandMultipleChoice.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/MultipleChoiceQn.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandEditTest.java
src/test/java/quizhub/command/CommandListTest.java
src/test/java/quizhub/command/CommandMarkTest.java
src/test/java/quizhub/command/CommandShortAnswerTest.java

Implement
toString method for printing questions to the screen
toSerializedString method for formatting question to file storage

Refactor code and fix some bugs

---

docs/team/spinoandraptos.md
docs/team/stevengx12.md

Add Guan Xiao PPP

---

src/main/java/quizhub/command/CommandMultipleChoice.java
src/main/java/quizhub/parser/Parser.java

Now catches if the user puts duplicate options

Catch duplicate options in mcq

---

src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/question/MultipleChoiceQn.java
src/main/java/quizhub/question/Question.java
src/main/java/quizhub/question/ShortAnsQn.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandStartTest.java

* Abstract validating of user answers and checking of user answers to the respective question classes
* Move redundant String literals to the start command object
* Fix bugs related to the escape characters used in the question storage
* Update tests for the start quiz command

Refactor code related to start quiz command

---

docs/UserGuide.md
src/main/java/quizhub/command/CommandDelete.java
src/main/java/quizhub/command/CommandStart.java
src/main/java/quizhub/parser/Parser.java
src/main/java/quizhub/questionlist/QuestionList.java
src/main/java/quizhub/storage/Storage.java
src/main/java/quizhub/ui/Ui.java
src/test/java/quizhub/command/CommandDeleteTest.java

* Ensure all commands in user guide work as expected
* Update helper text in codes
* Fix bug in start command where questions are deleted after a quiz
* Fix bug in creating mcq from CLI or file without bound checking for answer

Review user guide and fix bugs

---

docs/DeveloperGuide.md
docs/UML/Puml/commandEdit.puml
src/main/java/quizhub/command/CommandEdit.java

Update DG for CommandEdit to include MCQ options

Update DG for CommandEdit

---

docs/DeveloperGuide.md

update DG for storage and ui

---

docs/team/stevengx12.md

update Guan Xiao PPP
